### ISSUE TITLE
接口不支持https

### ISSUE THREAD

**Issue by xiedong11** [TLingC/QZAPI#2]
接口不支持https，跑在app或者部署在http服务器上的web项目还可以，但是如果项目部署的服务器开启https这套接口就不能正常运行了，希望作者把接口兼容到https

**Comment by TLingC** [comment]
你的教务系统本身支不支持https呢？

**Comment by TLingC** [comment]
看了你的代码，如果你教务系统不支持https访问，而你又要在例如微信小程序这种只允许https请求的场景下部署的话，就只能自己封装一遍，在后端而不要在前端调用接口。

**Comment by xiedong11** [comment]
不是我的教务系统不支持，是接口不支持，我的React项目部署在https服务上，你的接口目前只支持http，所以这块办法再继续封装一层，两种解决方案，要么就是我放弃使用https服务，要么就是你把部署在你服务器上的项目加一层SSL，把服务兼容到https，我留言就是想问下，你接口有打算升级到https的打算吗，如果没有的话，我就想其他解放方案了，楼主辛苦

**Comment by TLingC** [comment]
https支持与否和我文档没有关系吧？
这是直接调用你教务系统上面自带的接口

**Comment by xiedong11** [comment]
好吧抱歉，是我搞错了，我以为楼主是接口服务的提供者呢，那是强智的接口服务没支持https，感谢楼主辛苦整理文档！
